name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        env:
          USER: root
          HOME_DIR: /root
        with:
          repository_root: .
          workdir: .
          buildozer_version: stable
          command: build

      - name: Show build output directory (debug)
        if: always()
        run: |
          echo "=== Root directory ==="
          ls -la || true
          echo "=== Bin directory ==="
          ls -la bin || true

      - name: Fix artifact permissions (best-effort)
        if: always()
        run: |
          if [ -d bin ]; then
            sudo chown -R $UID:$GID bin || true
            sudo chmod -R a+r bin || true
          fi

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zigzag-racer-apk
          path: bin/*.apk
